// export const Getidx ='Getidx'
// export const BlankDuoxuan ='BlankDuoxuan'
// export const HandleShowDialog ='HandleShowDialog'
// export const OnfxClick ='OnfxClick'
// export const HandleClose ='HandleClose'
// export const AddTodo = 'AddTodo'
// export const Shanchu = 'Shanchu'
// export const Zhiding = 'Zhiding'
// export const Selectdelect ='Selectdelect'
// export const Duoxuan = 'Duoxuan'
export const GetUser = 'GetUser'
export const GetUserREQ = 'GetUserREQ'
export const GetUserFAI = 'GetUserFAI'
export const GetLesson_REQ = 'GetLesson_REQ'
export const GetLesson_SUC = 'GetLesson_SUC'
export const GetLesson_FAI = 'GetLesson_FAI'

