export default {
  SEARCH_STUDENT_LIST_BY_OPTION: 'SEARCH_STUDENT_LIST_BY_OPTION',

  FETCH_USER_INFO: 'FETCH_USER_INFO',
  FETCH_LESSON_INFO: 'FETCH_LESSON_INFO',
  FETCH_STUDENT_LIST: 'FETCH_STUDENT_LIST',
  FETCH_CLASS_INFO: 'FETCH_CLASS_INFO',
  FETCH_LESSON_SATISFIED_INFO: 'FETCH_LESSON_SATISFIED_INFO',
  REPLY_USER_FEED_BACK: 'REPLY_USER_FEED_BACK',
  Fetchhomework: 'Fetchhomework',
  Fetchhomework2: 'Fetchhomework2',
  Fetchhomework3: 'Fetchhomework3',
  Fetchhomework4: 'Fetchhomework4',
  Fetchid: 'Fetchid',
  Sendmid: 'Sendmid',
  Sendword: 'Sendword',
  Fitchimg: 'Fitchimg',
  Addpower: 'Addpower',
  Setpower: 'Setpower',
  Cutpower: 'Cutpower',
  Deletepower: 'Deletepower',
  Sendid: 'Sendid',
  Reset: 'Reset',
  Upward: 'Upward',
  Leftward: 'Leftward',
  Downward: 'Downward',
  Rightward: 'Rightward',
  Initialize: 'Initialize',
  Random: 'Random',
  Gameover: 'Gameover'
};
