export const HandleShowDialog ='HandleShowDialog'
export const OnfxClick ='OnfxClick'
export const HandleClose ='HandleClose'
export const AddTodo = 'AddTodo'
export const Shanchu = 'Shanchu'
export const Zhiding = 'Zhiding'
export const Duoxuan = 'Duoxuan'
